version: '3.2'
services:
  couchdb:
    image: couchdb
    ports:
      - 5984:5984
  fauxton:
    image: 3apaxicom/fauxton
    depends_on:
      - couchdb
    ports:
      - 8000:8000
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://mec-poc:5984"
    extra_hosts:
      - "mec-poc: 10.2.40.162"