version: '3.2'
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mec-poc/portainer_data:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - 8081:8081
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "video-file-name:10:1,split-video-file:5:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - zookeeper
  job_dispatcher:
    image: ssriram1978/job_dispatcher:latest
    depends_on:
      - kafka
      - zookeeper
    hostname: job_dispatcher
    environment:
      video_file_path_key: /data
      broker_name_key: kafka:9092
      topic_key: video-file-name
    volumes:
      - /home/mec-poc/fromMobile:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  machine_learning_workers:
    image: ssriram1978/machine_learning_workers
    deploy:
      replicas: 1
#      resources:
#        limits:
#          cpus: "0.8"
#          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "5903:5900"
    depends_on:
      - kafka
      - zookeeper
      - redis
    hostname: machine_learning_workers
    environment:
      video_file_path_key: /data
      broker_name_key: kafka:9092
      topic_key: video-file-name
      case_url_key: http://mec-demo/synopsis/
      browser_loc_key: google-chrome
      browser_name_key: chrome
      case_name_key: MEC-POC
      login_username_key: Brief
      login_password_key: Cam
      image_directory: image_cont
      redis_server_hostname_key: mec-demo
      redis_server_port_key: 6379
      redis_log_keyname_key: briefcam-events
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/var/run/dbus/system_bus_socket'
    volumes:
      - /home/mec-poc/fromMobile:/data
      #- /home/sriramsridhar/PycharmProjects/briefcam/rtsp_recorder:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "mec-demo: 10.2.40.160"
      - "mec-poc: 10.2.40.162"
  couchdb:
    image: couchdb
    ports:
      - 5984:5984
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  fauxton:
    image: 3apaxicom/fauxton
    depends_on:
      - couchdb
    ports:
      - 8000:8000
    command:
      - sh
      - "-c"
      - "fauxton -c http://mec-poc:5984"
    extra_hosts:
      - "mec-poc: 10.2.40.162"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  front_end:
    image: ssriram1978/front_end:latest
    depends_on:
        - couchdb
    environment:
      couchdb_server_key: couchdb:5984
      database_name_key: briefcam
      id_to_container_name_key: id_to_container
      image_name_key: ssriram1978/rtsp_recorder:latest
      environment_key: video_file_path_key=/data min_file_size_key=10000000 rtsp_file_name_prefix_key=briefcam rtsp_duration_of_the_video_key=30 rtsp_capture_application_key=openRTSP
      bind_mount_key: /home/mec-poc/fromMobile:/data /etc/timezone:/etc/timezone:ro /etc/localtime:/etc/localtime:ro
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  elk:
    image: ssriram1978/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
    - LOGSTASH_HOST=mecpoc-ProLiant-BL460c-Gen9
    - LOGSTASH_PORT=5044
    - SHIPPER_NAME=mec
    extra_hosts:
    - "mec-poc: 10.2.40.162"
