version: '3.2'
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mec-poc/portainer_data:/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "video-file-name:10:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  docker_producer:
    image: ssriram1978/docker_producer:latest
    depends_on:
      - kafka
      - zookeeper
    hostname: docker_producer
    environment:
      video_file_path_key: /data
      broker_name_key: kafka:9092
      topic_key: video-file-name
    volumes:
      - /home/mec-poc/fromMobile:/data
  docker_consumer:
    image: ssriram1978/docker_consumer:latest
    deploy:
      replicas: 10
#      resources:
#        limits:
#          cpus: "0.8"
#          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "5903:5900"
      - "5904:5900"
      - "5905:5900"
      - "5906:5900"
      - "5907:5900"
      - "5908:5900"
      - "5909:5900"
      - "5910:5900"
      - "5911:5900"
      - "5912:5900"
    depends_on:
      - kafka
      - zookeeper
      - redis
    hostname: docker_consumer
    environment:
      video_file_path_key: /data
      broker_name_key: kafka:9092
      topic_key: video-file-name
      case_url_key: http://mec-demo/synopsis/
      browser_loc_key: google-chrome
      case_name_key: MEC-POC
      login_username_key: Brief
      login_password_key: Cam
      image_directory: image_cont
      redis_server_hostname_key: mec-demo
      redis_server_port_key: 6379
      redis_log_keyname_key: briefcam-events
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/var/run/dbus/system_bus_socket'
    privileged: true
    volumes:
      - /home/mec-poc/fromMobile:/data
    extra_hosts:
      - "mec-demo: 192.168.1.61"
