version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-beta30
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-enterprise-kafka:5.0.0-beta30
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
  docker_producer:
    image: ssriram1978/docker_producer:latest
    depends_on:
      - zookeeper
      - broker
    hostname: docker_producer
    environment:
      video_file_path_key: /data
      broker_name_key: broker:9092
      topic_key: video-file-name
    volumes:
      - /home/sriramsridhar/PycharmProjects/briefcam/data:/data
  docker_consumer:
    image: ssriram1978/docker_consumer:latest
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.2"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "5903:5900"
      - "5904:5900"
      - "5905:5900"
      - "5906:5900"
      - "5907:5900"
      - "5908:5900"
      - "5909:5900"
      - "5910:5900"
      - "5911:5900"
      - "5912:5900"
    depends_on:
      - zookeeper
      - broker
    hostname: docker_consumer
    environment:
      video_file_path_key: /data
      broker_name_key: broker:9092
      topic_key: video-file-name
      case_url_key: http://mec-demo-host/synopsis/
      browser_loc_key: google-chrome
      case_name_key: MEC-POC
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/var/run/dbus/system_bus_socket'
    privileged: true
    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /var/run/dbus/:/var/run/dbus/:ro
#      - /tmp:/tmp
#      - /dev/shm:/dev/shmdocke
      - /home/sriramsridhar/PycharmProjects/briefcam/data:/data
#    command:
#       - "sh"
#       - "-c"
#       - "/opt/bin/entry_point.sh"
#       - " &&"
#       - " sudo python3 /docker_consumer/poll_for_new_filename/poll_for_new_filename.py &"
    extra_hosts:
      - "mec-demo-host: 10.2.40.160"