version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "split-video-file:5:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  couchdb:
    image: couchdb
    ports:
      - 5984:5984
  fauxton:
    image: 3apaxicom/fauxton
    depends_on:
      - couchdb
    ports:
      - 8000:8000
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://mec-poc:5984"
    extra_hosts:
      - "mec-poc: 10.1.100.100"
  front_end:
    image: ssriram1978/front_end:latest
    depends_on:
        - couchdb
    environment:
      broker_name_key: kafka:9092
      topic_key: split-video-file
      couchdb_server_key: couchdb:5984
      database_name_key: briefcam
  rtsp_recorder:
    image: ssriram1978/rtsp_recorder:latest
    depends_on:
        - couchdb
        - kafka
#    deploy:
#      replicas: 5
    environment:
      video_file_path_key: /data
      broker_name_key: kafka:9092
      topic_key: split-video-file
    volumes:
      - /home/mec-poc/fromMobile:/data
